### ISSUE TITLE
Issue with reloader for `apistar run` on Windows.

### ISSUE THREAD

**Issue by audiolion** [encode/apistar#208] opened 2017-06-12 12:56 UTC
After the discussion on discourse, and #196 , #207 I think we can say there is an issue with windows.

From the discussion on discourse it looks like the issue is with the `app = get_current_app()` line, where the app isn't being properly obtained. This is based on the comment that when pasting the app into `run.py` it worked

`get_current_app()` is defined in [cli.py](https://github.com/tomchristie/apistar/blob/master/apistar/cli.py#L20) and I bet the issue is with the path resolution on windows. I don't have a windows system to test it out though, but all one would need to do is put a `import pdb; pdb.set_trace()` statement at the start of that function and step through to see where the path is resolving too.

**Comment by thelazysysadmin** [comment] 2017-06-12 13:28
Hi, not sure if this relevant but Pycharm is going mental with the formatting, could it be down to UNIX character encodings vs Windows?

**Comment by tomchristie** [comment] 2017-06-12 13:34
Thanks for digging into this, @audiolion!

**Comment by ithinkiborkedit** [comment] 2017-06-12 17:10
Filepath is "resolving" correctly: C:\Users\<name>\python_projects\TESTING_API_STAR\app.py

Have you tried using os.chdir() to yield the same result?

**Comment by audiolion** [comment] 2017-06-12 17:45
yeah after I wrote this I looked at the cli.py code and I saw that apistar would throw an informative error message if it couldnt get the app. so in that case I would just keep stepping through to find the problem code in `run.py` and then dig in from there

**Comment by androiddrew** [comment] 2017-06-13 19:27
I have been looking into this myself as I am using a windows machine too. Line 26 gets called then I get that nonsense error citing line 1 from  apistar.exe. I think the issue is definitely with the parameters passed to `run_simple()`. Dropping the use_reloader resolved the issue:

 `run_simple(host, port, app.wsgi, use_debugger=True, extra_files=['app.py'])`

So the issue appears to be related to werkzueg.serving. Looking at the source comments it does seem like they are advising against using this functionality.

**Comment by androiddrew** [comment] 2017-06-13 20:57
Ok issue is definitely in werkzueg [https://github.com/pallets/werkzeug/blob/master/werkzeug/_reloader.py#L118](https://github.com/pallets/werkzeug/blob/master/werkzeug/_reloader.py#L118) our friends are for some odd reason checking for both Windows OS and if the Python version is 2. If  True  they re-encode the arguments to subprocess.call in latin1. No clue why it was necessary to check for Python 2.

**Comment by androiddrew** [comment] 2017-06-13 21:55
c:\users\uskaxb07\env\fresh\scripts\python.exe C:\Users\uskaxb07\env\fresh\Scripts\apistar.exe run are the arguments that werkzueg is passing to `subprocess.call()` which it is getting from https://github.com/pallets/werkzeug/blob/master/werkzeug/_reloader.py#L53  and sure enough trying to call python.exe apistar.exe run will produce the error:

SyntaxError: Non-UTF-8 code starting with '\x90' in file C:\Users\uskaxb07\env\fresh\Scripts\apistar.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

No clue what can be done about it...

**Comment by androiddrew** [comment] 2017-06-14 19:11
A one line change would resolve the issue in Werkzueg. https://github.com/pallets/werkzeug/issues/1136

**Comment by audiolion** [comment] 2017-06-15 03:01
But does that change break anything else? Awesome work diving into this @androiddrew

**Comment by androiddrew** [comment] 2017-06-15 14:25
I am struggling to write an automated test to prove that. Issue is a little compounded because I have never made a pull request(no time like the present) and I only know how to mock tests with unittest.mock which I think is python 3 only.  Manually testing hasn't uncovered any issues and really thinking through all of the execution paths you should never be passing Python.exe a Windows PE or PE32+ file. 

I'll try to talk to someone on the Werkzueg IRC about it.

**Comment by lmr2391** [comment] 2017-07-26 13:21
Is there a possibility to run APIStar on Windows without using the CLI? E.g. You can run Flask using app.run() from within the Python module or typing `flask run` to the bash

**Comment by tomchristie** [comment] 2017-08-04 14:44
> Is there a possibility to run APIStar on Windows without using the CLI?

@lmr2391 Once https://github.com/tomchristie/apistar/pull/235 is released then yes.

    if __name__ == '__main__':
        app.main()

^^ This will work.

**Comment by androiddrew** [comment] 2017-08-15 13:37
I have just resigned myself to running the app without the werkzeug reloader when using a Windows machine.

`python -m werkzeug.serving app:app.wsgi`

**Comment by tomchristie** [comment] 2017-08-17 10:21
This should work now... `python app.py run`
We could still do with resolving this issue fully, tho.

**Comment by androiddrew** [comment] 2018-01-02 20:17
Alright, I have some good 2018 news for you all. Werkzeug 0.14.01 included my PR and I just confirmed that the reloader now works for windows under that version.  Think we can shut this one down.

**Comment by tomchristie** [comment] 2018-03-26 14:53
Thanks @androiddrew!

**Closed by tomchristie** 2018-03-26 14:53 UTC
Labels: Bug
